### ISSUE TITLE
Do not update Array.prototype

### ISSUE THREAD

**Issue by leandrohlsilva** [chovy/humanparser#33] opened 2018-09-24 14:40 UTC
The line https://github.com/chovy/humanparser/commit/f06d306e1fa9794ffc8023a561b45507240d682c#diff-168726dbe96b3ce427e7fedce31bb0bcR3

breaks projects.
By modifying Array.prototype, you will cause a bunch of undesirable behaviours, like:
```
for (var index in []) {
  console.log(index);
}
```
outputs
```
undefined
diff
```

Please, don't modify Array.prototype.

**Comment by leandrohlsilva** [comment] 2018-09-24 14:40
@chovy could you please have a look?

**Comment by dottodot** [comment] 2018-09-24 15:45
Duplicate of #32

**Comment by dottodot** [comment] 2018-09-24 15:47
You need to use v1.7.0 until it's fixed

**Closed** 2018-09-25 19:05 UTC
